# <span style="color:rgb(213,80,0)">ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ LINIOWYCH</span>

## Przykład prostej eliminacji Gaussa — tworzenie macierzy trójkątnej

Poniższy skrypt realizuje metodę Gaussa, celem której jest wytworzenie macierzy trójkątnej, a następnie rozwiązanie układu metodą podstawiania wstecznego. Funkcja implementująca metodę składa się z tych dwóch bloków.

Wykorzystywane są operacje elementarne:

1. Znalezienie wspólnego mianownika, który pozwoli wyzerować żądany element (algorytm przesuwa się po kolumnach)
2. Wykonanie operacji elementarnej → odjęcie wielokrotności wiersza
3. Ta implementacja nie wykorzystuje operacji elementarnej II → nie wszystkie układy równań mogą być sprowadzone do postaci macierzy trójkątnej bez przestawiania równań

Spróbuj poeksperymentować z budową macierzy i znaleźć taką, której sprowadzić do postaci trójkątnej się nie da.


In [1]:
def solveGauss(A, b):
    # Praca na kopii, aby nie modyfikować oryginału
    A = A.copy()
    b = b.copy()
    s = len(A)

    # Produkowanie macierzy trójkątnej
    for j in range(s - 1):
        for i in range(s - 1, j, -1):
            m = A[i, j] / A[j, j]          # Znajdowanie wspólnego mianownika
            A[i, :] -= m * A[j, :]         # Odejmowanie wielokrotności wiersza
            b[i] -= m * b[j]               # To samo robimy na wektorze b
        print(f"Eliminacja kolumny {j+1}, wynik:")
        print(A)
        print("Przekształceniu uległ również wektor b:")
        print(b)
        print()

    # Rozwiązanie — podstawianie wsteczne
    x = np.zeros(s)
    x[s - 1] = b[s - 1] / A[s - 1, s - 1]
    for i in range(s - 2, -1, -1):
        sump = 0.0
        for j in range(s - 1, i, -1):
            sump += A[i, j] * x[j]
        x[i] = (b[i] - sump) / A[i, i]
    return x


In [2]:
import numpy as np

# Przykładowa macierz układu równań
A = np.array([[-0.2106,  0.4656, -0.4531,  0.7106],
              [-0.6018,  0.2421, -0.8383,  1.3634],
              [ 0.0773, -0.5600,  0.4168, -0.2733],
              [ 0.7945,  1.0603,  1.5393,  0.0098]], dtype=float)

# Tutaj wpisz własną macierz:

# Wektor b → rozwiązaniem jest wektor samych jedynek
b = A.sum(axis=1).copy()

# Rozwiązanie metodą eliminacji Gaussa (naiwnej)
x = solveGauss(A, b)
print("\nRozwiązanie x:", x)
print("Sprawdzenie (A·x ≈ b?):", np.allclose(A @ x, b))


Eliminacja kolumny 1, wynik:
[[-0.2106      0.4656     -0.4531      0.7106    ]
 [ 0.         -1.08837521  0.45645584 -0.66717493]
 [ 0.         -0.38910313  0.25049122 -0.01247673]
 [ 0.          2.81680142 -0.17004449  2.6905773 ]]
Przekształceniu uległ również wektor b:
[ 0.5125     -1.2990943  -0.15108865  5.33733424]

Eliminacja kolumny 2, wynik:
[[-0.2106      0.4656     -0.4531      0.7106    ]
 [ 0.         -1.08837521  0.45645584 -0.66717493]
 [ 0.          0.          0.08730448  0.22604382]
 [ 0.          0.          1.01129945  0.96387564]]
Przekształceniu uległ również wektor b:
[ 0.5125     -1.2990943   0.3133483   1.97517509]

Eliminacja kolumny 3, wynik:
[[-0.2106      0.4656     -0.4531      0.7106    ]
 [ 0.         -1.08837521  0.45645584 -0.66717493]
 [ 0.          0.          0.08730448  0.22604382]
 [ 0.          0.          0.         -1.65452364]]
Przekształceniu uległ również wektor b:
[ 0.5125     -1.2990943   0.3133483  -1.65452364]


Rozwiązanie x: [1. 1. 1.

## Wykorzystywane funkcje

| Funkcja | Opis |
|---------|------|
| `np.allclose(a, b)` | Sprawdza czy dwa wektory są przybliżenie równe (tolerancja `rtol=1e-5`) |
| `A.copy()` | Tworzy niezależną kopię macierzy/vektora |
| `A.sum(axis=1)` | Sumuje elementy wierszy macierzy |
